# Use the official NGINX image
FROM nginx:alpine

# Copy the HTML, CSS, and JS files to the NGINX server directory
COPY ./frontend /usr/share/nginx/html

# Expose the port NGINX will serve on
EXPOSE 80
